GET http://localhost:3001/api/nots HTTP/1.1

############

POST http://localhost:3001/api/notes HTTP/1.1
Content-Type: application/json

{
    "content": "",
    "important": true
}

############

GET http://localhost:3001/api/notes/5f9481057e16bed157b1740c HTTP/1.1

############
